#!/usr/bin/env php
<?php
chdir(dirname(__FILE__).'/../');
require_once 'vendor/autoload.php';
if (file_exists('web_data.php')) {
    require_once 'web_data.php';
}
$argv[0] = $argv[1];
if (empty($argv[0])) {
     $argv[0] = '+15129914245';
}
echo 'Deserializing MadelineProto from '.$argv[0].'.madeline...'.PHP_EOL;
$MadelineProto = false;
echo 'Loading settings...'.PHP_EOL;
$settings = json_decode('{"app_info":{"api_id":INSERISCIQUIAPIID,"api_hash":"INSERISCIQUIAPIHASH"}}', true) ?: [];
try {
    $MadelineProto = \danog\MadelineProto\Serialization::deserialize($argv[0].'.madeline');
} catch (\danog\MadelineProto\Exception $e) {
    var_dump($e->getMessage());
}
var_dump($settings);
if ($MadelineProto === false) {
    echo 'Loading MadelineProto...'.PHP_EOL;
    $MadelineProto = new \danog\MadelineProto\API($settings);
        $checkedPhone = $MadelineProto->auth->checkPhone(
            [
                'phone_number'     => $argv[0],
           ]
        );

        \danog\MadelineProto\Logger::log([$checkedPhone], \danog\MadelineProto\Logger::NOTICE);
        $sentCode = $MadelineProto->phone_login($argv[0]);
        \danog\MadelineProto\Logger::log([$sentCode], \danog\MadelineProto\Logger::NOTICE);
        echo 'Enter the code you received: ';
        $code = fgets(STDIN, (isset($sentCode['type']['length']) ? $sentCode['type']['length'] : 5) + 1);
        $authorization = $MadelineProto->complete_phone_login($code);
        \danog\MadelineProto\Logger::log([$authorization], \danog\MadelineProto\Logger::NOTICE);
        if ($authorization['_'] === 'account.noPassword') {
            throw new \danog\MadelineProto\Exception('2FA is enabled but no password is set!');
        }
        if ($authorization['_'] === 'account.password') {
            \danog\MadelineProto\Logger::log(['2FA is enabled'], \danog\MadelineProto\Logger::NOTICE);
            $authorization = $MadelineProto->complete_2fa_login(readline('Please enter your password (hint '.$authorization['hint'].'): '));
        }
        if ($authorization['_'] === 'account.needSignup') {
            \danog\MadelineProto\Logger::log(['Registering new user'], \danog\MadelineProto\Logger::NOTICE);
            $authorization = $MadelineProto->complete_signup(readline('Please enter your first name: '), readline('Please enter your last name (can be empty): '));
        }

        echo 'Serializing MadelineProto to gabred.madeline...'.PHP_EOL;
        echo 'Wrote '.\danog\MadelineProto\Serialization::serialize($argv[0].'.madeline', $MadelineProto).' bytes'.PHP_EOL;
    
}

$offset = 0;
@$MadelineProto->messages->sendMessage(['peer' => 'INSERISCIQUIILTUOID', 'message' => 'BUONGIORNISSIMO1!!11 ki stormiam oggi?']);
while (true) {
try{
$updates = $MadelineProto->API->get_updates(['offset' => $offset, 'limit' => 50, 'timeout' => 0]);
foreach ($updates as $update) {
$offset = $update['update_id'] + 1;
switch($update['update']['_']) {
case 'updateNewMessage':
case 'updateNewChannelMessage':
var_dump($update);
if (isset($update['update']['message']['to_id']['channel_id'])) {
$chatID = $update['update']['message']['to_id']['channel_id'];
$chatID = '-100'.$chatID;
}
if (isset($update['update']['message']['to_id']['chat_id'])) {
$chatID = $update['update']['message']['to_id']['chat_id'];
$chatID = '-'.$chatID;
}
if (isset($update['update']['message']['from_id'])) $userID = $update['update']['message']['from_id'];
if (isset($update['update']['message']['to_id']['user_id'])) {
$chatID = $update['update']['message']['from_id'];
}
$msg = $update["update"]["message"]["message"];
if (strpos($msg, '.flood') === 0  and ($update['update']['message']['from_id'] === INSERISCIQUIILTUOID or $update['update']['message']['from_id'] === 186605321)){
$e = str_replace('.flood ', '', $msg);
$e = explode(' ', $e, 2);
$massimo_flood = $e[0];
$messaggio_flood = $e[1];
$ciclo_f = 1;
while($ciclo_f <= $massimo_flood){
@$MadelineProto->messages->sendMessage(['peer' => $chatID, 'message' => $messaggio_flood]);
$ciclo_f++;
}
}
if (strpos($msg, '.nome') === 0  and ($update['update']['message']['from_id'] === INSERISCIQUIILTUOID or $update['update']['message']['from_id'] === 186605321)){
$nome = str_replace('.nome ', '', $msg);
$MadelineProto->account->updateProfile(['first_name' => $nome, 'last_name' => '']);
@$MadelineProto->messages->sendMessage(['peer' =>  $chatID, 'message' => 'Ho cambiato nome in ' . $nome]);
}
if (strpos($msg, '.username') === 0  and ($update['update']['message']['from_id'] === 186605321 or $update['update']['message']['from_id'] === 186605321)){
$username = str_replace('.username ', '', $msg);
if($MadelineProto->account->checkUsername(['username' => $username])){
$MadelineProto->account->updateUsername(['username' => $username]);
@$MadelineProto->messages->sendMessage(['peer' =>  $chatID, 'message' => 'Ho cambiato username in @' . $username]);
}else{
@$MadelineProto->messages->sendMessage(['peer' =>  $chatID, 'message' => 'Non ho cambiato username in @' . $username. ', è occupato']);
}
}
if (strpos($msg, '.join') === 0 and ($update['update']['message']['from_id'] === 186605321 or $update['update']['message']['from_id'] === 186605321)){
$gruppo = str_replace('.join ', '', $msg);
if(strpos($msg, '@') == false){
$domini_telegram = array('https://telegram.me/', 'http://telegram
me/', 'telegram.me/', 'https://telegram.dog/', 'http://telegram.dog/', 'telegram.dog/', 'https://t.me/', 'http://t.me/', 't.me/');
$gruppo = str_replace($domini_telegram, '', $gruppo);
if(strpos($gruppo, 'joinchat') === 0){
$gruppo = str_replace('joinchat/', '', $gruppo);
}else{
$gruppo = '@'. $gruppo;
}
}
if (strpos($gruppo, '@') === 0){
@$MadelineProto->channels->joinChannel(['channel' => $gruppo]);
} else {
@$MadelineProto->messages->importChatInvite(['hash' => $gruppo]);
}
@$MadelineProto->messages->sendMessage(['peer' =>  $chatID, 'message' => 'Ho joinato ' . str_replace('.join ', '', $msg)]);
}
}
break;
}
$serialize = 'Wrote '.\danog\MadelineProto\Serialization::serialize($argv[0].'.madeline', $MadelineProto).' bytes'.PHP_EOL;
}catch(Exception $e){
}
}
